openapi: 3.0.0
info:
  title: Ares Labs
  version: 0.0.1
  contact:
    name: Ares Labs
    url: ares.koenk.be
    email: contact@ares.koenk.be
  termsOfService: 'https://ares.koenk.be/tos'
  description: We provide a smart security package that will help you keep your properties and businesses safe.
x-internal: false
tags:
  - name: image
servers:
  - url: 'http://localhost:8080'
    description: Local
  - url: 'https://project-ii.ti.howest.be/mars-06'
    description: Production
paths:
  /api/scan:
    post:
      tags:
        - image
      summary: Scan an image
      description: 'Our advanced AI system can scan an image and attempt to identify any known faces within it using our database. Based on the results of this analysis, a threat level will be determined on a scale from 0 to 1.'
      operationId: scanImage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  threat_level:
                    type: number
                    minimum: 0
                    maximum: 1
                    exclusiveMinimum: true
                    exclusiveMaximum: true
                    example: 0.42
              examples:
                Example:
                  value:
                    threat_level: 0.42
      requestBody:
        content:
          image/*:
            schema:
              type: string
              format: binary
        description: Provide raw image
